### ISSUE TITLE
[Feat]: Add Monitoring Integration for LangChain framework

### ISSUE THREAD

**Issue by patcher99** [openlit/openlit#139]
### 🚀 What's the Problem?
Currently we support LLM Monitoring integration when directly using official SDKs. LangChain is a popular choice when building RAG based applications but Doku doesn't support monitoring it currently

### 💡 Your Dream Solution
Similar setup as OpenAI Monitoring, Build a LLM monitoring integration for LangChain

### 🤔 Seen anything similar?
NA

### 🖼️ Pictures or Drawings
NA

### 👐 Want to Help Make It Happen?
- [ ] Yes, I'd like to volunteer and help out with this!

**Comment by codefromthecrypt** [comment]
I see this tagged for openlit-js, but looks like it isn't implemented yet, right? should we re-open this, or add a new issue?
