### ISSUE TITLE
Add Getting Started Steps in the UI

### ISSUE THREAD

**Issue by patcher99** [openlit/openlit#18]
### 🚀 What's the Problem?
When we login into the Doku UI for the first time (When we haven't created an API Key or sent any data) the UI should show some instructions. The instructions should be such that all values are already added in the provided snippet. 

### 💡 Your Dream Solution
NA

### 🤔 Seen anything similar?
NA

### 🖼️ Pictures or Drawings
NA
### 👐 Want to Help Make It Happen?
- [x] Yes, I'd like to volunteer and help out with this!

**Comment by AmanAgarwal041** [comment]
Duplicate issue https://github.com/dokulabs/doku/issues/71 . Its already addressed in https://github.com/dokulabs/doku/pull/73
