### ISSUE TITLE
[Feat]: Support for Monitoring Haystack and LlamaIndex Frameworks

### ISSUE THREAD

**Issue by kjoth** [openlit/openlit#226]
### 💡 Your Dream Solution
Haystack and LlamaIndex are prominent frameworks in the field of GenAI. Requesting support for these frameworks in OpenLIT.

Haystack: https://github.com/deepset-ai/haystack

LlamaIndex: https://github.com/run-llama/llama_index

**Comment by amanagarwal042** [comment]
Thanks @kjoth 
The integration has been tested and now available in openlit python sdk `1.3.0`
