### ISSUE TITLE
Build a dashboard/Mixin for Grafana Cloud

### ISSUE THREAD

**Issue by patcher99** [openlit/openlit#24]
### 🚀 What's the Problem?
While Doku, is capable of exporting metrics to Grafana Cloud, we currently do not provide any premade dashboards or alert configurations for our users. This absence of initial setup tools forces users to spend additional time and effort crafting their own dashboards to monitor their data effectively. This step poses a challenge for users who may not be familiar with best practices for dashboard creation in Grafana, potentially leading to suboptimal monitoring setups.

### 💡 Your Dream Solution
The ideal solution would be the development of a comprehensive monitoring mixin for Grafana Cloud tailored specifically for Doku's exported metrics. This mixin would include:

- **Predefined Dashboards:** Prebuilt dashboard to display LLM Monitoring data processed by Doku' in a clear, insightful manner. These dashboards would highlight key performance indicators and provide users with an immediate overview of their system's health.

### 🖼️ Pictures or Drawings
NA

### 👐 Want to Help Make It Happen?
- [ ] Yes, I'd like to volunteer and help out with this!

**Comment by Aparna-Tyagi** [comment]
Hi, do we have monitoring mixin available for grafana cloud?
