### ISSUE TITLE
[Question]: maybe `reset_to_defaults()` do not call `fetch_pricing_info()`

### ISSUE THREAD

**Issue by CherishCai** [openlit/openlit#267]
In the OpenlitConfig, should `reset_to_defaults()`  change `cls.pricing_info = fetch_pricing_info()` to `cls.pricing_info = {}` ?
It seems that `update_config()` will still be called `fetch_pricing_info()` again.

https://github.com/openlit/openlit/blob/86dde16719bccc2bbbd56bf33d7005b58c086da6/sdk/python/src/openlit/__init__.py#L69

**Comment by amanagarwal042** [comment]
Hey @CherishCai 

`fetch_pricing_info()` would still be called once and if empty it would return {}. We could reset_to_defaults() but that technically what `fetch_pricing_info()` covers considering its returns {} if the pricing cant be found

**Comment by CherishCai** [comment]
@patcher9 Thanks for your reply.
It seem to be twice HTTP remote calls now, so look forward to reducing one.

**Comment by amanagarwal042** [comment]
Do you wanna prepare a PR for you idea?

**Comment by CherishCai** [comment]
Oh, it's an honor to be a contributor when I get to know `openlit` better.

**Comment by CherishCai** [comment]
I debugged it locally, added `print()`, and saw that there were indeed two calls to `fetch_pricing_info()`. 

so will make a PR for `reset_to_defaults()` change `cls.pricing_info = fetch_pricing_info()` to `cls.pricing_info = {}`.

![image](https://github.com/openlit/openlit/assets/16837364/91c4780a-9836-4f3c-89fd-d95b025c42a2)
