### ISSUE TITLE
[Typo]: Some typos about GenAI Response in SemanticConvetion

### ISSUE THREAD

**Issue by CherishCai** [openlit/openlit#294]
Are there any typos?

https://github.com/openlit/openlit/blob/5d2d20524a94df768ceb21292e691496c1e4fa38/sdk/python/src/openlit/semcov/__init__.py#L62-L68

maybe change L66-L68
```python
    GEN_AI_RESPONSE_IMAGE_SIZE = "gen_ai.request.image_size"
    GEN_AI_RESPONSE_IMAGE_QUALITY = "gen_ai.request.image_quality"
    GEN_AI_RESPONSE_IMAGE_STYLE = "gen_ai.request.image_style"
```

to 

```python
    GEN_AI_RESPONSE_IMAGE_SIZE = "gen_ai.response.image_size"
    GEN_AI_RESPONSE_IMAGE_QUALITY = "gen_ai.response.image_quality"
    GEN_AI_RESPONSE_IMAGE_STYLE = "gen_ai.response.image_style"
```

**Comment by amanagarwal042** [comment]
Hey @CherishCai , Good catch. I

 think it needs to be the other way round. the values are correct, the variable names are wrong as its collected from the request metadata itself. So it should be

```
  GEN_AI_REQUEST_IMAGE_SIZE = "gen_ai.request.image_size"
  GEN_AI_REQUEST_IMAGE_QUALITY = "gen_ai.request.image_quality"
  GEN_AI_REQUEST_IMAGE_STYLE = "gen_ai.request.image_style"
```

and since this is a variable change, the naming would need to change across the entire SDK code. Lemme know if you wanna contribute it as a PR?

**Comment by CherishCai** [comment]
@patcher9 I wanna contribute it as a PR. 
And these codes need to be moved to line 55( under `GEN_AI_REQUEST_TRAINING_FILE = "gen_ai.request.training_file"`), Is that right?

**Comment by amanagarwal042** [comment]
Ill keep this issue open for now until `GEN_AI_REQUEST_IMAGE_QUALITY` and `GEN_AI_REQUEST_IMAGE_STYLE` are also updated. Would you also wanna PR these two up?

**Comment by CherishCai** [comment]
> Ill keep this issue open for now until `GEN_AI_REQUEST_IMAGE_QUALITY` and `GEN_AI_REQUEST_IMAGE_STYLE` are also updated. Would you also wanna PR these two up?

@patcher9 It was modified together at https://github.com/openlit/openlit/pull/295

**Comment by amanagarwal042** [comment]
yeah this is good to close. I mistakenly just went with the PR title.

Thanks @CherishCai as always!!
