### ISSUE TITLE
[Feat]: Remove the Span `StatusCode=OK` requirement to follow OTel Trace spec

### ISSUE THREAD

**Issue by ThomasVitale** [openlit/openlit#300]
### 🚀 What's the Problem?
Telemetry from instrumented applications is only included in the OpenLit UI if the related span `StatusCode` is `OK`. When using the OpenLit library, that's not a problem since that is done as part of the instrumentation. However, when integrating other libraries/applications, it becomes a problem if they follow the OTel Trace specification and keep the `StatusCode` unset in successful scenarios.

### 💡 Your Dream Solution
It would be great if the span `StatusCode=OK` requirement could be removed, perhaps converting that into a filter to exclude spans with an explicit `StatusCode=ERROR`. The OpenTelemetry Trace Specification ([spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.34.0/specification/trace/api.md#set-status)) includes the following about the status:

> Generally, Instrumentation Libraries SHOULD NOT set the status code to Ok, unless explicitly configured to do so. Instrumentation Libraries SHOULD leave the status code as Unset unless there is an error, as described above.
> 
> Application developers and Operators may set the status code to Ok.

Furthermore, the [OTel semantic conventions](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#status) includes the following about the status of HTTP interactions: 

> [Span Status](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.33.0/specification/trace/api.md#set-status) MUST be left unset if HTTP status code was in the 1xx, 2xx or 3xx ranges, unless there was another error (e.g., network error receiving the response body; or 3xx codes with max redirects exceeded), in which case status MUST be set to Error.

### 📖 Additional Context
I really like OpenLit, congratulations on such a great library and thanks for following the OpenTelemetry path. It makes it possible to integrate even more systems with OpenLit. I'm currently working on integrating Java applications with OpenLit, and thanks to the OpenTelemetry adoption is more approachable. The main challenge I'm experiencing is about the `unset` span status code instead of `OK`, which is why I raised this issue.

**Comment by amanagarwal042** [comment]
Good call out, really appreciate this one. 

This makes sense and I like the idea of keeping it configurable from the user's end.

Lemme know if you would like to raise a PR for this

**Comment by ThomasVitale** [comment]
@patcher9 Thanks for the quick reply. I'd be happy to contribute a PR!

* I can update the default filter in https://github.com/openlit/openlit/blob/main/src/client/src/helpers/platform.ts#L228 so that if a StatusCode is specified, that will be used. If not, it would include all spans where StatusCode is not ERROR (basically, including both OK and UNSET statuses).
* How about the instrumentation? Do you want me to remove the places where the spans are set to OK status?

**Comment by amanagarwal042** [comment]
For the UI, We can query for both OK and UNSET. Kinda like an or condition I think.

For the SDK Instrumentation I think, We can add a flag (bool) if the user wants status as OK in spans, If that is a True we set status as OK, else default will be UNSET
```
if set_ok:
  span.set_status(Status(StatusCode.OK))
```

Ideally if we don't set anyting, UNSET should be applied by default. Lemme know if it makes sense

**Comment by ThomasVitale** [comment]
Yes, it does, thank you! How should the flag for the span status be provided by users? Via the `openlit.init()` method?

**Comment by amanagarwal042** [comment]
yup, via `openlit.init()`

**Comment by ThomasVitale** [comment]
Perfect, thanks. I started working on it.

**Comment by amanagarwal042** [comment]
Lemme know if you are stuck anywhere. Happy to help!

**Comment by ThomasVitale** [comment]
@patcher9 thanks! I've been away on a conference and didn't have much time to complete the PR, but now I'm back and I'll continue to work on it. I plan to submit a draft PR in the next few days for some early review.

**Comment by AmanAgarwal041** [comment]
@ThomasVitale I have addressed the client traces for the condition for status ok only, but if you feel that it should be addressed from the python sdk as well, feel free to re-open this issue. Thanks

**Comment by ThomasVitale** [comment]
@AmanAgarwal041 thank you so much for handling the status code change!

I've been struggling with the Python SDK update to make the status code configurable. It's been a while since I worked with Python, so it took me a bit of time to navigate the source code and didn't manage to meet the timeline I initially expected, sorry about that. I'm fine with not having that change, though, so it's ok for me to keep this issue closed.
