### ISSUE TITLE
[Bug]: No Traces on langchain_community.llms.Ollama

### ISSUE THREAD

**Issue by moonbaseDelta** [openlit/openlit#301]
Hi, somehow I get no traces if using Langchain' Ollama, but all seems fine with raw Ollama package:

 
```
from ollama import Client
import openlit

openlit.init( otlp_endpoint="http://127.0.0.1:4318" )
client = Client(host='http://localhost:11434') 
response = client.chat(model="aya:8b"  , messages=[
  { 'role': 'user', 'content': 'Why is the sky blue?', },
])
#### That produce traces, all good
```

```
from langchain_community.llms import Ollama
import openlit

openlit.init( otlp_endpoint="http://127.0.0.1:4318" )

llm = Ollama(model="aya:8b", base_url="http://localhost:11434" )
response = llm.invoke("Tell me a joke")
print(response )
#### ?? no traces
```

I use Win11, and I've tried different versions of LangChain and OpenLit - does not work. 
Also checked it on machine with Win10 - same story.

**Comment by moonbaseDelta** [comment]
As far as I understand, current wrapping over LangChain Ollamas is not implemented: https://github.com/openlit/openlit/blob/main/sdk/python/src/openlit/instrumentation/langchain/__init__.py

I've read over LangChain code and I agree that it's complicated way too much.


However there're `langchain_core/tracers` which seems to address exact stuff OpenLit is's missing: https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/tracers/base.py

So, is there a plan for that part of tracing? Or may you provide a guidance what shoud be done in `instrumentation` to make use of LangChain's tracers?

**Comment by amanagarwal042** [comment]
Yeah, LangChain seems to not be using the Ollama SDK underneath which causes this issue. 

Tracers wont work I think here as they are not in OpenTelemetry format (recommended format for Tracing), Though I can create wrappers around the LLM Invoke function directly (That might lead to duplicate traces though I think when using say OpenAI).

Ill try a few things out this week and get back on the best possible route for this. Thanks for letting us know!!!!

**Comment by amanagarwal042** [comment]
Update:
Able to figure out a way to trace all LLMs under langchain_community. I will hopefully be making a release today or early tommorow. Will update you here in the thread

**Comment by amanagarwal042** [comment]
Closing this issues as fixed in OpenLIT sdk version `1.14.2`

If its still relevant, Feel free to reopen

**Comment by jradikk** [comment]
@patcher9 is it possible to also add support for langchain_community.chat_models module? If i use the following module, openlit doesn't generate traces as opposed to using langchain_community.llms module

```python
from langchain_community.chat_models import ChatOllama

llm = ChatOllama(
        base_url=base_url,
        model=model_name
        )
response = llm.invoke("Tell me a joke")
print(response)
```

Thanks

**Comment by amanagarwal042** [comment]
Yup, Sure can do! 
Ill get that added (Still need to scope it out and check feasability)
Will update you with my findings

@jradikk Can you open a new feature request issue for this?
