### ISSUE TITLE
[Bug]: Failed to instrument langchain: type object 'BaseLoader' has no attribute 'aload'

### ISSUE THREAD

**Issue by nkkrishnakfk** [openlit/openlit#305]
### 🐛 What's Going Wrong?
> When starting the langchain based application, getting the following error,  - 
   
"Failed to instrument langchain: type object 'BaseLoader' has no attribute 'aload'"

Possibly Impacting: Traces 

Log: 
----
INFO:     Will watch for changes in these directories: ['/app']
INFO:     Uvicorn running on http://0.0.0.0:443 (Press CTRL+C to quit)
INFO:     Started reloader process [8] using StatReload
Failed to instrument langchain: type object 'BaseLoader' has no attribute 'aload'
INFO:     Started server process [14]
INFO:     Waiting for application startup.
INFO:     Application startup complete.

### 📸 Any Screenshots?
No traces are displayed.
<img width="830" alt="Screenshot 2024-06-28 at 4 02 34 PM" src="https://github.com/openlit/openlit/assets/49898295/39393439-666b-46f0-b4bf-3fa47033c7af">

### 💻 Your Setup

langchain                                0.1.4
langchain-community                      0.0.14
langchain-core                           0.1.23
langchain-openai                         0.0.5
langgraph                                0.0.15
langsmith                                0.0.87
openai                                   1.35.7
openlit                                  1.14.1

**Comment by amanagarwal042** [comment]
Hey @nkkrishnakfk Thanks for raising the issue. I think there is some issue with the 0.1.4 version as 0.1.1 works well for me. I am trying to resolve another langchain [issue](https://github.com/openlit/openlit/issues/297). Ill include this as part of my fix

**Comment by amanagarwal042** [comment]
Okay I was able to replicate this, If you use `langchain-community >= 0.1.20` it should work as intended. Apologies on my behalf for not mentioning the correct version in our docs, Ill get it fixed now

**Comment by amanagarwal042** [comment]
Closing this issues as fixed in OpenLIT sdk version `1.14.2`

If its still relevant, Feel free to reopen
