### ISSUE TITLE
[Bug]: incompatibilities with LLM semantics

### ISSUE THREAD

**Issue by codefromthecrypt** [openlit/openlit#316]
### 🐛 What's Going Wrong?

As a first timer, I tried the ollama instrumentation, and sent a trace to a local collector. Then I compared the output with [llm semantics defined by otel](https://opentelemetry.io/docs/specs/semconv/gen-ai/llm-spans/). I noticed some incompatibilities and a lot of attributes not yet defined.

### 🕵️ Steps to Reproduce

make an ollama chat instrumented with openlit and look at the trace data sent to the collector

### 🎯 What Did You Expect?

otel specs should be a subset of openlit semantics, so no incompatible attributes. I would expect an issue tracking incompatabilities.

### 📸 Any Screenshots?

Semantically, we can only discuss [spans](https://opentelemetry.io/docs/specs/semconv/gen-ai/llm-spans) as there are not yet semantics defined for metrics.

compatible:
* kind=client
* name=ollama.chat
* attributes['telemetry.sdk.name']='openlit' (defined in resource semantics)
* attributes['gen_ai.system']='ollama'
* attributes['gen_ai.request.model']='llama3'
* attributes['gen_ai.usage.prompt_tokens']=31
* attributes['gen_ai.usage.completion_tokens']=11

incompatible:
* attributes['gen_ai.prompt']='[chat](user: <|fim_prefix|>def hello_world():<|fim_suffix|><|fim_middle|>)' (should be an event attribute, not a span attribute)
* attributes['gen_ai.completion']='def hello_world():' (should be an event attribute, not a span attribute)
* attributes['gen_ai.response.finish_reason']='stop' (should be finish_reasons and an array)

not yet defined in the standard:
* attributes['gen_ai.operation.name']='chat'
* attributes['gen_ai.endpoint']='ollama.chat'
* attributes['gen_ai.environment']='default'
* attributes['gen_ai.application_name']='openlit-python-ollama'
* attributes['gen_ai.request.is_stream']=false
* attributes['gen_ai.usage.total_tokens']=43
* attributes['gen_ai.usage.cost']=0

### 💻 Your Setup
- OpenLIT Version: [e.g., 0.0.1]
- OpenLIT SDK Version: [e.g., 0.0.3]
- Deployment Method: [Helm, Docker]

### 👐 Want to Help Make It Happen?
- [ ] Yes, I'd like to volunteer and help out with this!

**Comment by amanagarwal042** [comment]
Hey @codefromthecrypt , As we have already discussed, we will be making these changes. I have created to seperate issues to track this. Closing this in favour of #317 and #318 

Thanks!
