### ISSUE TITLE
[Bug]:Empty panels on SigNoz dashboards

### ISSUE THREAD

**Issue by dev-gabrielchaves** [openlit/openlit#324]
### 🐛 What's Going Wrong?
>  Explain the bug. Tell us what's happening that shouldn't be.

Problem related on:
https://openlit.slack.com/archives/C0712FM210U/p1720553279900999

### 🕵️ Steps to Reproduce
>  To see the bug, what steps should we follow?

### 🎯 What Did You Expect?
>  Describe what you thought would happen.

### 📸 Any Screenshots?
>  Pictures can say a thousand words and can be super helpful!

### 💻 Your Setup
- OpenLIT Version: [e.g., 0.0.1]
- OpenLIT SDK Version: [e.g., 0.0.3]
- Deployment Method: [Helm, Docker]

### 📝 Additional Notes
>  Got more to say? Tell us here.

### 👐 Want to Help Make It Happen?
- [ ] Yes, I'd like to volunteer and help out with this!

**Comment by amanagarwal042** [comment]
As discussed, This doesn't seem to be an issue as of now so closing this. Thanks for raising this!
