### ISSUE TITLE
[Feat]: Add OpenTelemetry instrumentation for monitoring vLLM

### ISSUE THREAD

**Issue by AlbertoManuel07** [openlit/openlit#328]
### 🚀 What's the Problem?
Lack of vLLM integration.

### 💡 Your Dream Solution
After the integration is completed, it will be a monitoring application that works on a larger scale.

### 🤔 Seen anything similar?
No

### 🖼️ Pictures or Drawings
No

### 👐 Want to Help Make It Happen?
- [ ] Yes, I'd like to volunteer and help out with this!

**Comment by amanagarwal042** [comment]
Thanks @AlbertoManuel07 for thsi feature request, I am now starting to work on this and will keep you updated as I go through this. In the meanwhile if you have any specific usecases or if you could share your workflow with vLLM, I can try to make sure that those are covered as I add this feature to OpenLIT. Thanks!

**Comment by amanagarwal042** [comment]
Also I just realised, You should be able to send traces directly from vLLM with `--otlp-traces-endpoint` aswell
