### ISSUE TITLE
[Bug]:Version Conflict Between OpenLit 1.16 and Qdrant-Client 1.9.0

### ISSUE THREAD

**Issue by knut-bw** [openlit/openlit#337]
### 🐛 What's Going Wrong?
>  Explain the bug. Tell us what's happening that shouldn't be.

I installed OpenLit 1.16 and Qdrant-Client 1.9.0 using Python 3. This caused a dependency conflict where grpcio-tools 1.65.1 requires protobuf <6.0dev, >=5.26.1, but I have protobuf 4.25.3, which is incompatible.

### 🕵️ Steps to Reproduce
>  To see the bug, what steps should we follow?
1. Install Qdrant-Client 1.9.0 using pip install qdrant-client==1.9.0.
2. Install OpenLit 1.16.0 using pip install openlit==1.16.0.

### 🎯 What Did You Expect?
>  Describe what you thought would happen.

I followed the versions specified in the documentation and expected that this issue would not occur.
### 📸 Any Screenshots?
>  Pictures can say a thousand words and can be super helpful!

![image](https://github.com/user-attachments/assets/ed580572-5e5d-452c-9857-9a8fee944e3e)
![image](https://github.com/user-attachments/assets/5423a964-9cd8-4994-920c-2ffd1b9d902e)
![image](https://github.com/user-attachments/assets/b9b70f32-bdf1-49f4-bb3b-9e4452f39352)
![image](https://github.com/user-attachments/assets/2e875ea3-8c30-4f95-bb24-5159c2695bd5)

### 💻 Your Setup
- OpenLIT Version: [1.16.0]
- Qdrant Python SDK client Version: [1.9.0]
- Deployment Method: [Docker]

### 📝 Additional Notes
>  Got more to say? Tell us here.

### 👐 Want to Help Make It Happen?
- [ ] Yes, I'd like to volunteer and help out with this!

**Comment by amanagarwal042** [comment]
Hey @knut-bw 
Thanks for raising this issue. 

Yeah grpcio-tools is not a direct dependency of OpenLIT but rather a dependency I think from the one of the opentelemetry package. I'll see if we can do a version bump on either and see if this can be sorted out. 

QQ, Is this causing any issues whehn using OpenLIT in your code?

**Comment by knut-bw** [comment]
Hello, sorry for the late reply. Actually, my deployment approach involves packaging the application into a container for execution. During the image build process, I encountered a package conflict issue when trying to install dependencies.

I resolved the issue by first running pip install -r requirements.txt in the Dockerfile, and then separately installing openlit. This allowed me to successfully build the image, but I am not yet sure if this solution will affect the normal operation of the application.

**Comment by amanagarwal042** [comment]
Gotcha, Thanks! That makes sense. Ill still look up if I am facing any issue. Also feel free to join our [Community Slack](https://join.slack.com/t/openlit/shared_invite/zt-2etnfttwg-TjP_7BZXfYg84oAukY8QRQ) if you wanna disuss or need help with anything.
