### ISSUE TITLE
[Bug]:Can't use it with LiteLLM - litellm 1.41.27 requires tiktoken>=0.7.0, but you have tiktoken 0.6.0 which is incompatible.

### ISSUE THREAD

**Issue by aluferraz** [openlit/openlit#339]
### 🐛 What's Going Wrong?
>  Following the docs, https://docs.openlit.io/latest/integrations/litellm I'm trying to add openlit to a litellm project, but it has a dependency conflict:

 litellm 1.41.27 requires tiktoken>=0.7.0, but you have tiktoken 0.6.0 which is incompatible.
 openlit 1.16.0 depends on tiktoken<0.7.0 and >=0.6.0

### 🕵️ Steps to Reproduce
Create a litellm project
pip install openlit

### 🎯 What Did You Expect?
Installation to be completed.

### 💻 Your Setup
- OpenLIT Version: 1.16.0
- Deployment Method: Docker

**Comment by amanagarwal042** [comment]
> openlit 1.16.0 depends on tiktoken<0.7.0 and >=0.6.0


Hey so we don't have this dependency as such as you can see https://github.com/openlit/openlit/blob/87be86c925a0bd213d48a69e8f7f3a847a46b807/sdk/python/pyproject.toml#L15

**Comment by amanagarwal042** [comment]
https://github.com/openlit/openlit/pull/340

I have created this PR to anycase use 0.0.7 as the version for tiktoken
