### ISSUE TITLE
Fix: Request Page load time, Date and Time for each request and sub-text for 

### ISSUE THREAD

**Issue by patcher99** [openlit/openlit#42]
### 🐛 What's Going Wrong?

- The load time for the request page is slow. The SQL Query itself returns pretty fast so probably the rendering of the UI elements is causing Load time issues
- Set default time as 24h for both pages(Dashboard and Requests) and ideally have the time interval be carried between the two pages (same on visiting)
- Add time to along with Date on each LLM request log panel
- Add sub-text like how we do for total token, cost etc in the LLM request log panel

### 🕵️ Steps to Reproduce
Go to the UI and checkout requests Page

### 🎯 What Did You Expect?
Explained above

### 📸 Any Screenshots?
NA

### 💻 Your Setup
- Doku Version: [e.g., 0.0.1]
- DokuMetry SDK: [Python or NodeJS]
- DokuMetry SDK Version: [e.g., 0.0.3]
- Deployment Method: [Helm, Linux, Windows, Doker]

### 📝 Additional Notes
NA

### 👐 Want to Help Make It Happen?
- [x] Yes, I'd like to volunteer and help out with this!

**Comment by AmanAgarwal041** [comment]
Distributed issues : 
- https://github.com/dokulabs/doku/issues/68
- https://github.com/dokulabs/doku/issues/69


Other issues are already been taken care of 👍 
- Add time to along with Date on each LLM request log panel
- Add sub-text like how we do for total token, cost etc in the LLM request log panel

Hence closing this one.
