### ISSUE TITLE
[Bug]: Unexpected API Tracing in OpenTelemetry with Grafana and Tempo

### ISSUE THREAD

**Issue by krishnarastogi** [openlit/openlit#474]
### 🐛 What's Going Wrong?
>  I'm using OpenTelemetry's auto-instrumentation with Grafana and Tempo to trace my application. However, when I run OpenLit, it starts logging traces for all API requests going to Grafana, rather than focusing solely on requests related to the LLM, vector database, or GPU.

### 🕵️ Steps to Reproduce
>  Start the application with OpenTelemetry auto-instrumentation configured.
Run OpenLit.

### 🎯 What Did You Expect?
>  I expected it to log only the traces from the file where I initialized OpenLit, focusing on specific components like the LLM, vector database, or GPU—rather than logging every API request going to Grafana.

### 📝 Additional Notes
>  If you have any sample configurations or recommendations to limit tracing data to the specific components (e.g., only LLM, vector database, or GPU-related requests), it would be greatly appreciated.

**Comment by amanagarwal042** [comment]
Hey @krishnarastogi 
OpenTelemetry auto-instrumentation traces all API requests
OpenLIT can only trace LLM, VectorDB and GPU requests

So if you just keep OpenLIT and remove OpenTelemetry auto-instrumentation, You should just see logging of LLM, VectorDB and GPU requests in Tempo

Happy to help futher!

**Comment by krishnarastogi** [comment]
Hey @patcher9 

Thanks so much for your reply!

I’m currently using Django/wsgi auto-instrumentation for logging, metrics, and traces specifically for the API requests in my backend application. Additionally, I’m exploring OpenLIT to log LLM observability separately, excluding the application’s API request data.

Could you suggest an approach to filter and route only the LLM, VectorDB, and GPU-related data to OpenLIT, possibly through service name configuration or another method? This would help maintain a clear separation between application API observability and LLM-focused observability to OpenLIT.

Additionally, I wanted to clarify: when we apply auto-instrumentation to an existing application and integrate OpenLIT alongside it, OpenLIT seems to start logging all requests—even if OpenTelemetry for OpenLIT is running as a separate container from the application’s OpenTelemetry container. Any insights on how to manage this behavior effectively?

**Comment by amanagarwal042** [comment]
If you want to filter LLM Observability traces in tempo, OpenLIT traces have the `telemetry.sdk.name ="openlit"` in resource attributes as well as the span attributes. So you can filter based on that

The dashboard available in this doc already has the filter built in for traces
https://docs.openlit.io/latest/connections/prometheus-tempo (Assuming you are using Prometheus backend for Metrics)

> Additionally, I wanted to clarify: when we apply auto-instrumentation to an existing application and integrate OpenLIT alongside it, OpenLIT seems to start logging all requests—even if OpenTelemetry for OpenLIT is running as a separate container from the application’s OpenTelemetry container. Any insights on how to manage this behavior effectively?

I think the filter in that case should still help as normal API requests traces should not have this attribute
