### ISSUE TITLE
[Bug]: Error when Tracing bedrock.converse with Image Message

### ISSUE THREAD

**Issue by chriskhanhtran** [openlit/openlit#501]
### 🐛 What's Going Wrong?
In the `bedrock` instrumentor, attempting to trace a `converse` function containing an image message triggers an error. The issue occurs at this [line](https://github.com/openlit/openlit/blob/0c41338bb53e20a3a4aa956769645146f3b504c6/sdk/python/src/openlit/instrumentation/bedrock/bedrock.py#L108), where the code tries to access `item["text"]` in message content. According to the [`converse`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/bedrock-runtime/client/converse.html) specification, content items do not contain a `type` key, causing a `KeyError` when the item is an image without a `text` key.

### 🕵️ Steps to Reproduce
1. Call the `converse` function with a `messages` payload that includes both text and image content:
    ```python
    response = client.converse(
        modelId='string',
        messages=[
            {
                'role': 'user',
                'content': [
                    {"text": "What is in the image?"},
                    {
                        'image': {
                            'format': 'png',
                            'source': {
                                'bytes': b'bytes'
                            }
                        }
                    }
                ]
            }
        ]
    )
    ```
2. Observe that an error is raised due to the absence of a `type` key and the lack of a `text` key for the image item.

![image](https://github.com/user-attachments/assets/dc416663-7559-4c9e-adbe-827dc9b8980d)

### 🎯 What Did You Expect?
I expected the `converse` function to handle non-text content items gracefully, logging only the text messages and ignoring items in byte format (e.g., images).

### 💻 Your Setup
- OpenLIT SDK Version: 1.29.3

### 📝 Additional Notes
Proposed solution: Update the code to log only text messages, ensuring that items in byte format are excluded. Here’s a code snippet to address the issue:

```python
content_str = ", ".join(f'text: {item["text"]}' for item in content if "text" in item)
```

### 👐 Want to Help Make It Happen?
- [x] Yes, I'd like to volunteer and help out with this!

**Comment by amanagarwal042** [comment]
Ahh I see, Yeah my bad for this. 
I see you wanna raise a fix yourself for this, incase you need help lemme know!

**Comment by chriskhanhtran** [comment]
@patcher9 thanks! I have opened PR #532 to handle this bug as well as #502.

**Comment by amanagarwal042** [comment]
Thanks @chriskhanhtran for the PR and the fix!
