### ISSUE TITLE
[Bug]: Hugging Face Transformers models tokens not displayed

### ISSUE THREAD

**Issue by ishachinniah-hds** [openlit/openlit#513]
### 🐛 What's Going Wrong?
> I am encountering an issue where OpenLIT is not able to pick up and display token metrics when using Hugging Face transformers models. Specifically, I am using the meta-llama/Llama-3.2-3B-Instruct model from Hugging Face, and when passing this model through a transformers pipeline and into a HuggingFacePipeline, followed by a RAG chain, OpenLIT does not show token usage information on the dashboard. Instead, it only displays the average request duration.

### 🕵️ Steps to Reproduce
>  I am using the "meta-llama/Llama-3.2-3B-Instruct" model from hugging face. I then pass the model into a transformers pipeline and HuggingFacePipeline before it is passed into a RAG chain. With OTEL_LOG_LEVEL=debug, I see the following error: Error in trace creation: expected string or buffer. Error in trace creation: 'HuggingFacePipeline' object has no attribute 'model'. Additionally the openlit dashboard displays average request duration, but no token usage information.

### 🎯 What Did You Expect?
>  I expected OpenLIT to display token usage metrics (e.g., tokens per request, tokens processed) alongside the average request duration, since OpenLIT is integrated with Hugging Face Transformers and supports token tracking.

### 📸 Any Screenshots?
>  
<img width="718" alt="Screenshot 2024-11-18 at 4 51 30 PM" src="https://github.com/user-attachments/assets/7fdfae69-38ee-4a7f-8158-d578a730a6b8">

### 💻 Your Setup
- OpenLIT Version: 1.29.3
- Hugging Face Model: meta-llama/Llama-3.2-3B-Instruct

**Comment by amanagarwal042** [comment]
Hey @ishachinniah-hds 

Working on a fix in this PR - https://github.com/openlit/openlit/pull/514

**Comment by amanagarwal042** [comment]
Hey @ishachinniah-hds 

I have released the fix in the version [1.30.5](https://pypi.org/project/openlit/1.30.5/). Thanks for finding and reporting the issue. 

Incase you still have issues with this, feel free to reopen this (or a new) issue.
