### ISSUE TITLE
[Bug]: Incorrect Token Usage representation in the Area Chart

### ISSUE THREAD

**Issue by Nidhin117** [openlit/openlit#515]
### 🐛 What's Going Wrong?
>  There are a couple of issues with the Token Usage graph:
- Value on Y axis does not correspond to the Max value (Total Tokens). This is because all 3 token usage values(prompt tokens, completion tokens and Total tokens) are stacked. Consequently Y axis displays a sum of all 3 stacked values. Ideally only 2 token usage values should be stacked and total tokens will be an implied value. in my screenshot , Y axis value is 56189. This value is determined by summing up Total tokens(28087), prompt tokens(18326) and completion tokens(9761) + 15.
-  The token usage is not stacked in the proper order. Lowest value should be dynamically placed first. In my case Completion tokens should be first, followed by prompt tokens. Sum of these should imply/indicate Total tokens.

### 🕵️ Steps to Reproduce
- Instrument any LLM app with OpenLIT
- Check the token usage graph

### 🎯 What Did You Expect?
> For issue 1 : Y axis value should be total tokens + 15 instead of total tokens + prompt tokens + completion tokens + 15
> For issue 2: Lowest value (completion tokens) is placed at the bottom followed by the next higher value (prompt tokens). Stacking order should be dynamically determined

### 📸 Any Screenshots?
![image](https://github.com/user-attachments/assets/c699141f-7cb8-4ebb-a096-f2a82bff5ae9)

### 💻 Your Setup
- OpenLIT Version: 1.11.2
- OpenLIT SDK Version: 1.24.1
- Deployment Method: [Docker]

### 📝 Additional Notes
>  Got more to say? Tell us here.

### 👐 Want to Help Make It Happen?
- [ ] Yes, I'd like to volunteer and help out with this!

**Comment by amanagarwal042** [comment]
Thanks @Nidhin117 for finding this, Yeah @AmanAgarwal041 will try to get a fix in for this.

**Comment by AmanAgarwal041** [comment]
Thanks @Nidhin117 for pointing this out. 
Area charts work pretty this way : 

> let's say if there are prompt token 4 , completion tokens 2 and total tokens 6
> then prompt tokens area points will start from 0-4, completion tokens will be from 4-6, and total tokens will be from 6-12.
> which is what is represented in the above chart.

But it's actually is confusing with the total tokens area in the chart. So, its better to keep just prompt tokens & completion tokens, which is what should be done in the above issue.

**Comment by amanagarwal042** [comment]
Hey @Nidhin117 The fix is now available in OpenLIT 1.11.3

**Comment by Nidhin117** [comment]
Hey @AmanAgarwal041  and @patcher9 , thanks for fixing this. It works as expected now.
