### ISSUE TITLE
[Bug]: Newline Escape issue with Prompt Hub

### ISSUE THREAD

**Issue by Kyle-DeepHealth** [openlit/openlit#530]
When you paste a prompt into prompt him which has new lines in it, save, then load the prompt and attempt to edit, the app ends up replacing all \n new line chats with \\n. And it will continue to do this as many times as you open and save the prompt. 

Workaround for now, edit the prompt in another tool and just store it in prompt hub.

**Comment by amanagarwal042** [comment]
@AmanAgarwal041 Can you take this up?

**Comment by amanagarwal042** [comment]
Hey @Kyle-DeepHealth , This should be fixed in OpenLIT-1.11.6.

Thanks for identifying the issue and letting us know, Really Appreciate it.
